name: Sync Fork

on:
  schedule:
    - cron: '0 6 * * *'   # cada día a las 06:00 UTC
  workflow_dispatch:         # también lo puedes ejecutar manualmente desde Actions

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Config Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream repo
        run: |
          git remote add upstream https://github.com/LeonardoGB29/ihc_web_project.git
          git fetch upstream

      - name: Merge upstream into fork
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories -m "Sync fork"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
